name = "BracketAlgebras"
uuid = "304cb2e1-bfe1-4bb6-af58-8b73a9a6b3c1"
authors = ["Sascha Stüttgen <sascha.stuettgen@rwth-aachen.de> and contributors"]
version = "1.0.0-DEV"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Bijections = "e2ed5e7c-b2de-5872-ae92-c73ca462fb04"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[compat]
Combinatorics = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
